Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\johnp_000\Documents\GitHub\HeadFirstPython\Chapter_2_DataTypes\vowels3.py 
Seach for vowels in this word:>>>aaaii
a:3
e:0
i:2
o:0
u:0
[1, 2, 3, 4]
>>> 
 RESTART: C:\Users\johnp_000\Documents\GitHub\HeadFirstPython\Chapter_2_DataTypes\vowels3.py 
Seach for vowels in this word:>>>dfgvfdvdzfbvsdf4efdgvfi
a:0
e:1
i:1
o:0
u:0
[1, 2, 3, 4]
>>> 
 RESTART: C:\Users\johnp_000\Documents\GitHub\HeadFirstPython\Chapter_2_DataTypes\vowels3.py 
Seach for vowels in this word:>>>iiieee
a was found 0 times
e was found 3 times
i was found 3 times
o was found 0 times
u was found 0 times
[1, 2, 3, 4]
>>> 
 RESTART: C:\Users\johnp_000\Documents\GitHub\HeadFirstPython\Chapter_2_DataTypes\vowels3.py 
Seach for vowels in this word:>>>aaaeeiiuo
a was found 3 times
e was found 2 times
i was found 2 times
o was found 1 times
u was found 1 times
[1, 2, 3, 4]
>>> 
 RESTART: C:\Users\johnp_000\Documents\GitHub\HeadFirstPython\Chapter_2_DataTypes\vowels3.py 
Seach for vowels in this word:>>>aaiie
Traceback (most recent call last):
  File "C:\Users\johnp_000\Documents\GitHub\HeadFirstPython\Chapter_2_DataTypes\vowels3.py", line 19, in <module>
    for k, v in sorted(found):
ValueError: not enough values to unpack (expected 2, got 1)
>>> 
 RESTART: C:\Users\johnp_000\Documents\GitHub\HeadFirstPython\Chapter_2_DataTypes\vowels3.py 
Seach for vowels in this word:>>>aaeeii
a was found 2 times(s).
e was found 2 times(s).
i was found 2 times(s).
o was found 0 times(s).
u was found 0 times(s).
>>> found
{'a': 2, 'e': 2, 'i': 2, 'o': 0, 'u': 0}
>>> 
 RESTART: C:\Users\johnp_000\Documents\GitHub\HeadFirstPython\Chapter_2_DataTypes\vowels3.py 
Seach for vowels in this word:>>>
a was found 0 times(s).
e was found 0 times(s).
i was found 0 times(s).
o was found 0 times(s).
u was found 0 times(s).
>>> 
 RESTART: C:\Users\johnp_000\Documents\GitHub\HeadFirstPython\Chapter_2_DataTypes\vowels3.py 
Seach for vowels in this word:>>>00000
a was found 0 times(s).
e was found 0 times(s).
i was found 0 times(s).
o was found 0 times(s).
u was found 0 times(s).
>>> 
 RESTART: C:\Users\johnp_000\Documents\GitHub\HeadFirstPython\Chapter_2_DataTypes\vowels3.py 
Seach for vowels in this word:>>>000aeevvv
adding a
adding e
adding e
a was found 1 times(s).
e was found 2 times(s).
i was found 0 times(s).
o was found 0 times(s).
u was found 0 times(s).
>>> 
 RESTART: C:/Users/johnp_000/Documents/GitHub/HeadFirstPython/Chapter_2_DataTypes/vowels5.py 
Seach for vowels in this word:>>>1212a
Traceback (most recent call last):
  File "C:/Users/johnp_000/Documents/GitHub/HeadFirstPython/Chapter_2_DataTypes/vowels5.py", line 12, in <module>
    found[letter] += 1
KeyError: 'a'
>>> fruits = {'apples
	      
SyntaxError: EOL while scanning string literal
>>> fruits = {'apples':0}
	      
>>> 'apples' in fruits
	      
True
>>> true
	      
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    true
NameError: name 'true' is not defined
>>> True
	      
True
>>> False
	      
False
>>> 
 RESTART: C:/Users/johnp_000/Documents/GitHub/HeadFirstPython/Chapter_2_DataTypes/vowels5.py 
Seach for vowels in this word:>>>aae
Traceback (most recent call last):
  File "C:/Users/johnp_000/Documents/GitHub/HeadFirstPython/Chapter_2_DataTypes/vowels5.py", line 12, in <module>
    found[letter] += 1
KeyError: 'a'
>>> 
 RESTART: C:/Users/johnp_000/Documents/GitHub/HeadFirstPython/Chapter_2_DataTypes/vowels5.py 
Seach for vowels in this word:>>>12313fdgfvv 
  was found 1 times(s).
1 was found 2 times(s).
2 was found 1 times(s).
3 was found 2 times(s).
d was found 1 times(s).
f was found 2 times(s).
g was found 1 times(s).
v was found 2 times(s).
>>> 
 RESTART: C:/Users/johnp_000/Documents/GitHub/HeadFirstPython/Chapter_2_DataTypes/vowels5.py 
Seach for vowels in this word:>>>
>>> 
 RESTART: C:/Users/johnp_000/Documents/GitHub/HeadFirstPython/Chapter_2_DataTypes/vowels5.py 
Seach for vowels in this word:>>>123321321
1 was found 3 times(s).
2 was found 3 times(s).
3 was found 3 times(s).
>>> 
 RESTART: C:/Users/johnp_000/Documents/GitHub/HeadFirstPython/Chapter_2_DataTypes/vowels5.py 
Seach for vowels in this word:>>>aedv
a was found 1 times(s).
e was found 1 times(s).
>>> found
	      
{'a': 1, 'e': 1}
>>> 
 RESTART: C:/Users/johnp_000/Documents/GitHub/HeadFirstPython/Chapter_2_DataTypes/vowels5.py 
Seach for vowels in this word:>>>aaeei
Traceback (most recent call last):
  File "C:/Users/johnp_000/Documents/GitHub/HeadFirstPython/Chapter_2_DataTypes/vowels5.py", line 22, in <module>
    fruit[letter] += 1
NameError: name 'fruit' is not defined
>>> 
 RESTART: C:/Users/johnp_000/Documents/GitHub/HeadFirstPython/Chapter_2_DataTypes/vowels5.py 
Seach for vowels in this word:>>>aaee
a was found 4 times(s).
e was found 4 times(s).
>>> 
 RESTART: C:/Users/johnp_000/Documents/GitHub/HeadFirstPython/Chapter_2_DataTypes/vowels5.py 
Seach for vowels in this word:>>>aaeee
a was found 2 times(s).
e was found 3 times(s).
>>> 
 RESTART: C:/Users/johnp_000/Documents/GitHub/HeadFirstPython/Chapter_2_DataTypes/vowels5.py 
Seach for vowels in this word:>>>aaieiee
a was found 2 times(s).
e was found 3 times(s).
i was found 2 times(s).
>>> vowels = {'a', 'e','i','o','u'}
	      
>>> vowels
	      
{'a', 'u', 'o', 'i', 'e'}
>>> vowels
	      
{'a', 'u', 'o', 'i', 'e'}
>>> vowels2 = set('aeiou')
	      
>>> vowels2
	      
{'a', 'u', 'o', 'i', 'e'}
>>> vowels3 = set('a','sf')
	      
Traceback (most recent call last):
  File "<pyshell#13>", line 1, in <module>
    vowels3 = set('a','sf')
TypeError: set expected at most 1 arguments, got 2
>>> vowels3 = {'de','fgf'}
	      
>>> vowels3
	      
{'fgf', 'de'}
>>> word =
	      
SyntaxError: invalid syntax
>>> word = 'hello'
	      
>>> u = vowels.union(set(word))
	      
>>> u
	      
{'h', 'a', 'u', 'o', 'l', 'i', 'e'}
>>> u = vowels.intersection(set(word))
	      
>>> u
	      
{'o', 'e'}
>>> word = 'hello'
	      
>>> word2 = 'my'
	      
>>> u = set(word).union(set(word2))
	      
>>> u
	      
{'m', 'h', 'o', 'l', 'y', 'e'}
>>> word2 = 'hell'
	      
>>> dif = set(word).difference(set(word2))
	      
>>> dif
	      
{'o'}
>>> 
 RESTART: C:/Users/johnp_000/Documents/GitHub/HeadFirstPython/Chapter_2_DataTypes/vowels7.py 
Seach for vowels in this word:>>>aaeeecvnj
a was found
e was found
>>> 
 RESTART: C:/Users/johnp_000/Documents/GitHub/HeadFirstPython/Chapter_2_DataTypes/vowels7.py 
Seach for vowels in this word:>>>aeiogcvbcgvb
a was found
e was found
i was found
o was found
>>> tup = ('a','e','i','o','u')
	      
>>> tup
	      
('a', 'e', 'i', 'o', 'u')
>>> tup.count
	      
<built-in method count of tuple object at 0x03D16F30>
>>> tup.count('a')
	      
1
>>> tup.index(0)
	      
Traceback (most recent call last):
  File "<pyshell#33>", line 1, in <module>
    tup.index(0)
ValueError: tuple.index(x): x not in tuple
>>> tup.index('i')
	      
2
>>> tup = ('String',)
	      
>>> tup
	      
('String',)
>>> type(tup)
	      
<class 'tuple'>
>>> tup
	      
('String',)
>>> people = {}
	      
>>> people['Ford'] = {'Name': 'Ford Perfect',
		      'Gender': 'Male',
		      'Occupation': 'Researcher',
		      'Home Planet': 'Betelgeuse Seven'}
	      
>>> people
	      
{'Ford': {'Name': 'Ford Perfect', 'Gender': 'Male', 'Occupation': 'Researcher', 'Home Planet': 'Betelgeuse Seven'}}
>>> people['Arther'] = {'Name': 'Arther',
		      'Gender': 'Male',
		      'Occupation': 'Dude',
		      'Home Planet': 'Earth'}
	      
>>> people['Steve'] = {'Name': 'Steve',
		      'Gender': 'Trans',
		      'Occupation': 'Pizza Guy',
		      'Home Planet': 'Mars'}

>>> people
	      
{'Ford': {'Name': 'Ford Perfect', 'Gender': 'Male', 'Occupation': 'Researcher', 'Home Planet': 'Betelgeuse Seven'}, 'Arther': {'Name': 'Arther', 'Gender': 'Male', 'Occupation': 'Dude', 'Home Planet': 'Earth'}, 'Steve': {'Name': 'Steve', 'Gender': 'Trans', 'Occupation': 'Pizza Guy', 'Home Planet': 'Mars'}}
>>> import pprint
	      
>>> pprint.pprint(people)
	      
{'Arther': {'Gender': 'Male',
            'Home Planet': 'Earth',
            'Name': 'Arther',
            'Occupation': 'Dude'},
 'Ford': {'Gender': 'Male',
          'Home Planet': 'Betelgeuse Seven',
          'Name': 'Ford Perfect',
          'Occupation': 'Researcher'},
 'Steve': {'Gender': 'Trans',
           'Home Planet': 'Mars',
           'Name': 'Steve',
           'Occupation': 'Pizza Guy'}}
>>> people['Arther']
	      
{'Name': 'Arther', 'Gender': 'Male', 'Occupation': 'Dude', 'Home Planet': 'Earth'}
>>> people['Arther']
KeyboardInterrupt
>>> people['Arther']['Gender']
	      
'Male'
>>> people['Arther'].keys
	      
<built-in method keys of dict object at 0x009BDCC0>
>>> people['Arther'].keys()
	      
dict_keys(['Name', 'Gender', 'Occupation', 'Home Planet'])
>>> people['Arther'].items()
	      
dict_items([('Name', 'Arther'), ('Gender', 'Male'), ('Occupation', 'Dude'), ('Home Planet', 'Earth')])
>>> people['Arther'].setdefault('newkey',0)
	      
0
>>> pprint.pprint(people)
	      
{'Arther': {'Gender': 'Male',
            'Home Planet': 'Earth',
            'Name': 'Arther',
            'Occupation': 'Dude',
            'newkey': 0},
 'Ford': {'Gender': 'Male',
          'Home Planet': 'Betelgeuse Seven',
          'Name': 'Ford Perfect',
          'Occupation': 'Researcher'},
 'Steve': {'Gender': 'Trans',
           'Home Planet': 'Mars',
           'Name': 'Steve',
           'Occupation': 'Pizza Guy'}}
>>> 
